# Generated by Django 5.1.3 on 2024-12-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartproduct",
            unique_together={("product", "cart")},
        ),
    ]
